server:
  port: 9000
  servlet:
    context-path: /

spring:
  application:
    name: happain-admin
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false

# mybatisplus 配置
mybatis-plus:
#  是否复用sql
  executorType: simple

  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      # 自增
      id-type: auto
      # 逻辑删除填充字段 1
      logicDeleteValue: 1
#      逻辑未删除
      logicNotDeleteValue: 0
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# 反爬虫
anti:
  reptile:
    manager:
      enabled: true #开启反爬虫
#      开启ip反扒
      ip-rule:
        enabled: true
#        5秒内最大请求数
        request-max-size: 15
        expiration-time: 5000
#        ip白名单
#        ignore-ip:
      ua-rule:
        enabled: true




wx:
  mp:
    useRedis: false
    key: happain-wx
    configs:
      #       码上帮你
      - appId: wxd1ec757fa230b79a # 第一个公众号的appid
        secret: e75f6e754fb44ac4055dc7c9819bb72f # 公众号的appsecret
        token: xiaozeguai # 接口配置里的Token值
        aesKey: yjKbhENXxxBwvAILgrfHO7oggdiqLxaOsgU2gcJoAsd # 接口配置里的EncodingAESKey值
      #        优优资料卡
      - appId: wxc2be1a790a6f9285 # 第二个公众号的appid，以下同上
        secret: 375ab91811a9aaafc9df39f7f5248e04
        token: youyou
        aesKey: JPdMqys8bIaliGoFfGmYfvLeluwDcYe26Vt0EgGXKpj






